import {
  IconAlertTriangle,
  IconArrowLeft,
  IconArrowLeftRhombus,
  IconArrowRight,
  IconBrandFacebook,
  IconBrandFacebookFilled,
  IconBrandGoogleFilled,
  IconBuildingHospital,
  IconCheck,
  IconChecks,
  IconChevronLeft,
  IconCircleCheck,
  IconCircleX,
  IconDeviceLaptop,
  IconEye,
  IconFile,
  IconFileCheck,
  IconFileFilled,
  IconHome,
  IconLayoutDashboard,
  IconLayoutDashboardFilled,
  IconLayoutSidebarLeftCollapse,
  IconLayoutSidebarRightCollapse,
  IconLogout,
  IconMail,
  IconMapPin,
  IconMapPinFilled,
  IconMenu2,
  IconMoon,
  IconPackage,
  IconPhone,
  IconPhotoUp,
  IconPlus,
  IconRefresh,
  IconSearch,
  IconSettings,
  IconSettingsFilled,
  IconShoppingCart,
  IconShoppingCartFilled,
  IconStar,
  IconSun,
  IconTrashXFilled,
  IconTruckDelivery,
  IconUpload,
  IconUser,
  IconX,
  TablerIcon,
} from "@tabler/icons-react";

export type IconType = TablerIcon;

export const Icons = {
  add: IconPlus,
  check: IconCheck,
  eye: IconEye,

  alertTriangle: IconAlertTriangle,
  checkCircle: IconCircleCheck,
  package: IconPackage,
  invoiceFilled: IconFileCheck,
  truck: IconTruckDelivery,
  checks: IconChecks,
  xCircle: IconCircleX,
  returnRequested: IconArrowLeftRhombus,
  refresh: IconRefresh,
  google: IconBrandGoogleFilled,
  arrowRight: IconArrowRight,
  arrowLeft: IconArrowLeft,
  facebook: IconBrandFacebookFilled,
  menu: IconMenu2,
  chevronLeft: IconChevronLeft,
  home: IconHome,
  uploadImage: IconPhotoUp,
  user: IconUser,
  logout: IconLogout,
  pharmacy: IconBuildingHospital,
  upload: IconUpload,
  delete: IconTrashXFilled,
  prescriptionFilled: IconFileFilled,
  prescription: IconFile,
  star: IconStar,
  search: IconSearch,
  sun: IconSun,
  moon: IconMoon,
  laptop: IconDeviceLaptop,
  close: IconX,
  mail: IconMail,
  phone: IconPhone,

  leftCollapse: IconLayoutSidebarLeftCollapse,
  rightCollapse: IconLayoutSidebarRightCollapse,

  dashboard: IconLayoutDashboard,
  dashboardFilled: IconLayoutDashboardFilled,

  cartFilled: IconShoppingCartFilled,
  cart: IconShoppingCart,

  addressFilled: IconMapPinFilled,
  address: IconMapPin,

  settingsFilled: IconSettingsFilled,
  settings: IconSettings,
};
